version: '2'

services:
  soon:
    build: src/.
    environment:
      - POSTGRES_USER=soon
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=soon
      - POSTGRES_HOST=soon-api_db_1
      - AMBIENTE=DESENV
      - HOST=localhost:3000
    ports:
      - "3000:3000"   #web service port
      - "5859:5859"   #debug port
    volumes:
      - ./:/soon
    networks:
        - soon-network
    working_dir: /soon
    command: sh -c "npm install && cd src && nodemon app.js"
    depends_on:
      - db
    container_name: soon
    
  db:
    build: database/.
    ports:
      - "5432:5432"
    networks:
        - soon-network

networks:
  soon-network:
    driver: bridge